### ISSUE TITLE
Bug: array iterator problem in for..in loop

### ISSUE THREAD

**Issue by ntwrick** [abs-lang/abs#112]
After the first use of an array in a for..in loop, the iterator seems to be stuck at the end of the array (forever).
```
⧐  a = [1,2,3]
⧐  for i in a {echo(i)}
1
2
3
⧐  for i in a {echo(i)}
⧐  for i in [a] {echo(i)}
[1, 2, 3]
⧐  for i in a {echo(i)}
⧐  a
[1, 2, 3]
⧐  b = a
⧐  for i in b {echo(i)}
⧐  b
[1, 2, 3]
```

**Comment by odino** [comment]
Good catch! Going to have a look at this soon!

**Comment by odino** [comment]
@ntwrick this should be fixed by https://github.com/abs-lang/abs/pull/114

Attaching a bunch of fresh builds. Do you mind trying this out just to confirm stuff works as expected now? Let me know if your platform is not in the one I just managed to build, I can draft a quick release with all the supported platforms.

[builds.zip](https://github.com/abs-lang/abs/files/2752304/builds.zip)

**Comment by ntwrick** [comment]
Confirmed working with linux-amd64. 
Could also use a build for linux-arm for RPi.
Thanks,
Rick

**Comment by odino** [comment]
Thanks!
