### ISSUE TITLE
Existing Language With Same Name

### ISSUE THREAD

**Issue by tandalf** [abs-lang/abs#201]
This probably doesn't matter at this stage, but while trying to find this project's page, I found this other programming language with the same name `ABS Language` http://docs.abs-models.org/

Just to give some heads up :smiley:

**Comment by odino** [comment]
We've been aware of that for some time but considering the fact that abs models is not popular  I don't think we should change name etc. Googling leads there since they've been at it for some years, but the language hasn't garnered much traction and I think it's ok to use the same name if the project hasn't really taken off in years.
