### ISSUE TITLE
[question] trap?  wait?

### ISSUE THREAD

**Issue by mcampbell** [abs-lang/abs#458]
Is there an `abs` equivalent for `trap`?  Specifically, `bash`'s `trap EXIT`, where you can set up a function or piece of code to run when the script exit, no matter how it exits, for cleanup.

Also, I see you can `.wait` for a specific system command to finish; is there a way to spawn off a BUNCH of commands in the background an `wait` for them all, without having to wait for each one in turn?

**Comment by odino** [comment]
Abs 2.6 will have deferred functions, is that what you're looking at:

https://github.com/abs-lang/abs/pull/431

For waiting, I'm still uncertain how to implement concurrency, so it might take a while for it. Though I assume once it's implemented, it will look very similar to Go's waitgroups.

**Comment by odino** [comment]
Let me know if we can close this issue.

By the way, for now in order to wait for multiple background commands I would suggest this approach:

* start all of your commands
* start a loop
  * wait 1s
  * loop through the command results and check for result.done
  * when all are done, exit the loop -- all commands have finished running

**Comment by mcampbell** [comment]
I guess you can close it; the question(s) are answered.
